const data = [
    {
        id: 1,
        title: "Certified Kubernetes Administrator (CKA)",
        price: 12000,
        lessons: "12 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/12/kubernetes-cka.png",
    },
    {
        id: 2,
        title: "Certified Kubernetes Application Developer (CKAD)",
        price: 14000,
        lessons: "14 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/11/course-image-ckad-w960.png",
    },
    {
        id: 3,
        title: "Docker for the Absolute Beginner",
        price: 7000,
        lessons: "8 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/06/docker-illustration-01.png",
    },
    {
        id: 4,
        title: "DevOps Pre-Requisite Course",
        price: 10000,
        lessons: "10 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/06/test_image-03-1024x604.png",
    },
    {
        id: 5,
        title: "The Linux Basics Course",
        price: 5000,
        lessons: "5 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/10/linux-01.png",
    },
    {
        id: 6,
        title: "Shell Scripts for Beginners",
        price: 9000,
        lessons: "11 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/10/SHELL_1_540px.png",
    },
    {
        id: 7,
        title: "Terraform for Beginners",
        price: 9000,
        lessons: "11 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/12/Doc_tera-02.png",
    },
    {
        id: 8,
        title: "Ansible Certification Preparation Course",
        price: 15000,
        lessons: "17 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/10/course-image-ansible-cert-w960.png",
    },
    {
        id: 9,
        title: "Kubernetes for the Absolute Beginners",
        price: 7000,
        lessons: "8 Lessons",
        img: "https://cdn-kodekloud.pressidium.com/wp-content/uploads/2020/11/course-image-kubernetes-1024x737.png",
    },
]